# Generated by Django 2.1.2 on 2018-10-31 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(help_text='Enter food name', max_length=20, unique=True, verbose_name='Food name')),
                ('image_location', models.CharField(help_text='Enter url location', max_length=100, unique=True, verbose_name='Image url')),
                ('average_price', models.PositiveIntegerField(default=0, verbose_name='Average price')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(help_text='Enter ingredient name', max_length=20, unique=True, verbose_name='Ingredient name')),
            ],
        ),
        migrations.CreateModel(
            name='Veggie',
            fields=[
                ('veggie_name', models.CharField(help_text='Enter veggie type', max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Veggie type')),
                ('item_name', models.ManyToManyField(to='khubkhaoapp.Item', verbose_name='Item name')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khubkhaoapp.Item', verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='non_veg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khubkhaoapp.Food', verbose_name='Ingredient'),
        ),
        migrations.AddField(
            model_name='food',
            name='veggie',
            field=models.ManyToManyField(to='khubkhaoapp.Veggie', verbose_name='Veggie Type'),
        ),
    ]
