# Generated by Django 2.1.2 on 2018-11-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khubkhaoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='veggie',
            field=models.ManyToManyField(blank=True, to='khubkhaoapp.Veggie', verbose_name='Veggie Type'),
        ),
    ]
